trigger:
- main

steps:
# Prepare Analysis Configuration task
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'http://52.172.211.26:9000/'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: $(PROJECTKEY)

# Run Code Analysis task
- task: SonarQubeAnalyze@5

# Publish Quality Gate Result task
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
